name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: true

jobs:
  alfred-snpt:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: bin/go.mod
          cache: false

      - name: Setup project
        run: make install

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          working-directory: bin

      - name: Build binary
        run: make build-bin
