name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CI: true

jobs:
  snpt-alfred-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Setup project
        run: make install

      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32

      - name: Run tests
        run: make test

      - name: Build binary
        run: make build-helper
