name: Release

on:
  push:
    tags: ['*']

jobs:
  alfred-snpt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup project
        run: make install

      - name: Build project
        run: make build

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/snpt.alfredworkflow
          token: ${{ secrets.DEPLOY_TOKEN }}
